export const CHAPTERS = [
  { number: 1, name_ar: "ٱلْفَاتِحَة", name_en: "Al-Fātiḥah", short: "Fātiḥah" },
  { number: 85, name_ar: "ٱلْبُرُوج", name_en: "Al-Burūj" },
  { number: 86, name_ar: "ٱلطَّارِق", name_en: "Aṭ-Ṭāriq" },
  { number: 87, name_ar: "ٱلْأَعْلَى", name_en: "Al-Aʿlā" },
  { number: 88, name_ar: "ٱلْغَاشِيَة", name_en: "Al-Ghāshiyah" },
  { number: 89, name_ar: "ٱلْفَجْر", name_en: "Al-Fajr" },
  { number: 90, name_ar: "ٱلْبَلَد", name_en: "Al-Balad" },
  { number: 91, name_ar: "ٱلشَّمْس", name_en: "Ash-Shams" },
  { number: 92, name_ar: "ٱلَّيْل", name_en: "Al-Layl" },
  { number: 93, name_ar: "ٱلضُّحَىٰ", name_en: "Aḍ-Ḍuḥā" },
  { number: 94, name_ar: "ٱلشَّرْح", name_en: "Ash-Sharḥ" },
  { number: 95, name_ar: "ٱلتِّين", name_en: "At-Tīn" },
  { number: 96, name_ar: "ٱلْعَلَق", name_en: "Al-ʿAlaq" },
  { number: 97, name_ar: "ٱلْقَدْر", name_en: "Al-Qadr" },
  { number: 98, name_ar: "ٱلْبَيِّنَة", name_en: "Al-Bayyinah" },
  { number: 99, name_ar: "ٱلزَّلْزَلَة", name_en: "Az-Zalzalah" },
  { number: 100, name_ar: "ٱلْعَادِيَات", name_en: "Al-ʿĀdiyāt" },
  { number: 101, name_ar: "ٱلْقَارِعَة", name_en: "Al-Qāriʿah" },
  { number: 102, name_ar: "ٱلتَّكَاثُر", name_en: "At-Takāthur" },
  { number: 103, name_ar: "ٱلْعَصْر", name_en: "Al-ʿAṣr" },
  { number: 104, name_ar: "ٱلْهُمَزَة", name_en: "Al-Humazah" },
  { number: 105, name_ar: "ٱلْفِيل", name_en: "Al-Fīl" },
  { number: 106, name_ar: "قُرَيْش", name_en: "Quraysh" },
  { number: 107, name_ar: "ٱلْمَاعُون", name_en: "Al-Māʿūn" },
  { number: 108, name_ar: "ٱلْكَوْثَر", name_en: "Al-Kawthar" },
  { number: 109, name_ar: "ٱلْكَافِرُون", name_en: "Al-Kāfirūn" },
  { number: 110, name_ar: "ٱلنَّصْر", name_en: "An-Naṣr" },
  { number: 111, name_ar: "ٱلْمَسَد", name_en: "Al-Masad" },
  { number: 112, name_ar: "ٱلْإِخْلَاص", name_en: "Al-Ikhlāṣ" },
  { number: 113, name_ar: "ٱلْفَلَق", name_en: "Al-Falaq" },
  { number: 114, name_ar: "ٱلنَّاس", name_en: "An-Nās" }
];
